# Generated by Django 5.1.7 on 2025-05-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
