# Generated by Django 5.1.7 on 2025-05-15 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bid_profile_image_bid_user_name_alter_bid_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(upload_to='commission_proofs/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
